name: quick_meals
description: A simple app for getting meal suggestions

version: 0.9.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.3.1
  cloud_firestore: ^0.9.7
  http: ^0.12.0+1
  url_launcher: ^5.0.2
  transparent_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0


flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/main.png"

flutter:
  uses-material-design: true

  assets:
    - assets/edamam.png 
    - assets/icons/Vegetarian.png
    - assets/icons/Vegan.png
    - assets/icons/Low-Carb.png